FROM jenkins/jenkins:lts-jdk17

USER root

# install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    rm -rf /var/lib/apt/lists/*

# add jenkins в docker группу
RUN usermod -aG docker jenkins

USER jenkins
